### ISSUE TITLE
LoadBalancer

### ISSUE THREAD

**Issue by ammarqq** [kontena/pharos-docs#111]
I'm trying to configure and install loadbalancer between masters nodes. I would like to ask there is a plugin to confugure load balancer between master nodes on kontena pharos , Or I have to do it manually using haproxy and keepalive ,on nodes outside the masters.

KR
Ammar.

**Comment by jnummelin** [comment]
@ammarqq Currently there's no addon/plugin to do that automatically.

You could actually, at least threoretically, create a haproxy with proper configs as a deamonset that targets only the masters and deploy that via [addon](https://www.pharos.sh/docs/addons/#creating-an-addon). Just make sure you put it into TCP mode as the apiserver needs to terminate the SSL to get client info etc.

**Comment by ammarqq** [comment]
I used DNS round robin with the same name k8s.xxxx.xxx for 3 ips of the master nodes, and all of them worked good  .

**Comment by jnummelin** [comment]
👍 

Sounds like we can close the issue then
